#include "nsISupports.idl"
#include "bwWord.idl"
#include "bwQuote.idl"

[scriptable, uuid(6b99e600-f68a-11dc-95ff-0800200c9a66)]
interface nsIbwLocalStorage : nsISupports
{
	void getWords(out PRUint32 cnto, [array, size_is (cnto), retval] out nsIbwWord datao);
	nsIbwWord getWord(in wstring id);
	nsIbwWord newWord();
	nsIbwQuote newQuote();
	short addWord(in nsIbwWord Word);
	short removeWord(in nsIbwWord Word);
	short getCountWords();
	void save();
};
