#include "nsISupports.idl"
#include "domstubs.idl"

[scriptable, uuid(a97ddcb0-f68a-11dc-95ff-0800200c9a66)]
interface nsIbwQuote: nsISupports
{
	attribute wstring word;
	attribute wstring url;
	attribute wstring title;
	attribute wstring paragraph;
	attribute wstring id;
	attribute nsIDOMElement element;
};
